name: Build and Deploy
on: [push]
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    environment: github-pages
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v1

      - name: Install and Build 🔧
        run: |
          npm install
          npm run-script build
        env: 
          FIREBASE_CONFIG: ${{ secrets.FIREBASE_CONFIG }}

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: dist

